apiVersion: v1
kind: Service
metadata:
  name: main-app-svc
spec:
  type: ClusterIP
  selector:
    app: main-app
  ports:
    - name: main-app
      port: 2345
      protocol: TCP
      targetPort: 8080
    - name: pong-app
      port: 2346
      protocol: TCP
      targetPort: 4000
